title: Spectacular Documentation
description: Advanced metacognitive domain-specific LLM for D3.js visualization development
baseurl: "/spectacular"
url: "https://fullscreen-triangle.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - api-reference.md
  - cognitive-architecture.md
  - tutorials/getting-started.md

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - script.js
  - styles.css 